import { db } from '@/db';
import { questions } from '@/db/schema';

async function main() {
    const sampleQuestions = [
        // EXAM 1 (Biology Mid-term, id: 1) - 8 questions
        {
            examId: 1,
            questionText: 'What is photosynthesis?',
            questionType: 'multiple_choice',
            optionA: 'The process by which plants convert light energy into chemical energy',
            optionB: 'The process by which animals digest food',
            optionC: 'The process of cell division in plants',
            optionD: 'The process of water absorption by roots',
            correctAnswer: 'The process by which plants convert light energy into chemical energy',
            points: 1,
            orderIndex: 0,
        },
        {
            examId: 1,
            questionText: 'Mitochondria are the powerhouse of the cell',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'True',
            points: 1,
            orderIndex: 1,
        },
        {
            examId: 1,
            questionText: 'Which organ pumps blood through the body?',
            questionType: 'multiple_choice',
            optionA: 'Liver',
            optionB: 'Heart',
            optionC: 'Lungs',
            optionD: 'Kidneys',
            correctAnswer: 'Heart',
            points: 1,
            orderIndex: 2,
        },
        {
            examId: 1,
            questionText: 'Name the process by which cells divide',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'Mitosis',
            points: 2,
            orderIndex: 3,
        },
        {
            examId: 1,
            questionText: 'What is DNA?',
            questionType: 'multiple_choice',
            optionA: 'A type of protein',
            optionB: 'The genetic material that carries hereditary information',
            optionC: 'A cellular organelle',
            optionD: 'A form of energy storage',
            correctAnswer: 'The genetic material that carries hereditary information',
            points: 2,
            orderIndex: 4,
        },
        {
            examId: 1,
            questionText: 'All plants perform photosynthesis',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'False',
            points: 2,
            orderIndex: 5,
        },
        {
            examId: 1,
            questionText: 'Which gas do plants absorb during photosynthesis?',
            questionType: 'multiple_choice',
            optionA: 'Oxygen',
            optionB: 'Nitrogen',
            optionC: 'Carbon dioxide',
            optionD: 'Hydrogen',
            correctAnswer: 'Carbon dioxide',
            points: 1,
            orderIndex: 6,
        },
        {
            examId: 1,
            questionText: 'What is the basic unit of life?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'Cell',
            points: 1,
            orderIndex: 7,
        },

        // EXAM 2 (World History Quiz, id: 2) - 6 questions
        {
            examId: 2,
            questionText: 'When did World War II end?',
            questionType: 'multiple_choice',
            optionA: '1943',
            optionB: '1945',
            optionC: '1947',
            optionD: '1950',
            correctAnswer: '1945',
            points: 1,
            orderIndex: 0,
        },
        {
            examId: 2,
            questionText: 'The Roman Empire fell in 476 AD',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'True',
            points: 2,
            orderIndex: 1,
        },
        {
            examId: 2,
            questionText: 'Who was the first President of the United States?',
            questionType: 'multiple_choice',
            optionA: 'Thomas Jefferson',
            optionB: 'George Washington',
            optionC: 'John Adams',
            optionD: 'Benjamin Franklin',
            correctAnswer: 'George Washington',
            points: 1,
            orderIndex: 2,
        },
        {
            examId: 2,
            questionText: 'What year did Christopher Columbus discover America?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: '1492',
            points: 1,
            orderIndex: 3,
        },
        {
            examId: 2,
            questionText: 'Which ancient civilization built the pyramids?',
            questionType: 'multiple_choice',
            optionA: 'Greeks',
            optionB: 'Romans',
            optionC: 'Egyptians',
            optionD: 'Mayans',
            correctAnswer: 'Egyptians',
            points: 1,
            orderIndex: 4,
        },
        {
            examId: 2,
            questionText: 'The Great Wall of China was built in the 20th century',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'False',
            points: 1,
            orderIndex: 5,
        },

        // EXAM 3 (Advanced Mathematics, id: 3) - 10 questions
        {
            examId: 3,
            questionText: 'Solve for x: 2x + 5 = 15',
            questionType: 'multiple_choice',
            optionA: 'x = 5',
            optionB: 'x = 10',
            optionC: 'x = 7.5',
            optionD: 'x = 2.5',
            correctAnswer: 'x = 5',
            points: 2,
            orderIndex: 0,
        },
        {
            examId: 3,
            questionText: 'What is the derivative of x^2?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: '2x',
            points: 2,
            orderIndex: 1,
        },
        {
            examId: 3,
            questionText: 'What is the value of π (pi) rounded to 2 decimal places?',
            questionType: 'multiple_choice',
            optionA: '3.12',
            optionB: '3.14',
            optionC: '3.16',
            optionD: '3.18',
            correctAnswer: '3.14',
            points: 1,
            orderIndex: 2,
        },
        {
            examId: 3,
            questionText: 'The square root of 144 is 12',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'True',
            points: 1,
            orderIndex: 3,
        },
        {
            examId: 3,
            questionText: 'Solve: 3x - 7 = 20',
            questionType: 'multiple_choice',
            optionA: 'x = 7',
            optionB: 'x = 9',
            optionC: 'x = 11',
            optionD: 'x = 13',
            correctAnswer: 'x = 9',
            points: 2,
            orderIndex: 4,
        },
        {
            examId: 3,
            questionText: 'What is the area formula for a circle?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'πr²',
            points: 2,
            orderIndex: 5,
        },
        {
            examId: 3,
            questionText: 'What is 25% of 200?',
            questionType: 'multiple_choice',
            optionA: '25',
            optionB: '50',
            optionC: '75',
            optionD: '100',
            correctAnswer: '50',
            points: 1,
            orderIndex: 6,
        },
        {
            examId: 3,
            questionText: 'A prime number has exactly two factors',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'True',
            points: 1,
            orderIndex: 7,
        },
        {
            examId: 3,
            questionText: 'What is the slope of the line y = 3x + 2?',
            questionType: 'multiple_choice',
            optionA: '2',
            optionB: '3',
            optionC: '5',
            optionD: '-3',
            correctAnswer: '3',
            points: 2,
            orderIndex: 8,
        },
        {
            examId: 3,
            questionText: 'Simplify: (x^3 * x^2)',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'x^5',
            points: 2,
            orderIndex: 9,
        },

        // EXAM 4 (Computer Science Fundamentals, id: 4) - 7 questions
        {
            examId: 4,
            questionText: 'What does CPU stand for?',
            questionType: 'multiple_choice',
            optionA: 'Central Processing Unit',
            optionB: 'Computer Personal Unit',
            optionC: 'Central Program Utility',
            optionD: 'Computational Processing Unit',
            correctAnswer: 'Central Processing Unit',
            points: 1,
            orderIndex: 0,
        },
        {
            examId: 4,
            questionText: 'Python is a compiled programming language',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'False',
            points: 2,
            orderIndex: 1,
        },
        {
            examId: 4,
            questionText: 'Which data structure uses LIFO?',
            questionType: 'multiple_choice',
            optionA: 'Stack',
            optionB: 'Queue',
            optionC: 'Array',
            optionD: 'Tree',
            correctAnswer: 'Stack',
            points: 2,
            orderIndex: 2,
        },
        {
            examId: 4,
            questionText: 'What does HTML stand for?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'HyperText Markup Language',
            points: 1,
            orderIndex: 3,
        },
        {
            examId: 4,
            questionText: 'What is the time complexity of binary search?',
            questionType: 'multiple_choice',
            optionA: 'O(n)',
            optionB: 'O(log n)',
            optionC: 'O(n^2)',
            optionD: 'O(1)',
            correctAnswer: 'O(log n)',
            points: 2,
            orderIndex: 4,
        },
        {
            examId: 4,
            questionText: 'RAM is a type of permanent storage',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'False',
            points: 1,
            orderIndex: 5,
        },
        {
            examId: 4,
            questionText: 'Which language is primarily used for web styling?',
            questionType: 'multiple_choice',
            optionA: 'JavaScript',
            optionB: 'HTML',
            optionC: 'CSS',
            optionD: 'Python',
            correctAnswer: 'CSS',
            points: 1,
            orderIndex: 6,
        },

        // EXAM 5 (Chemistry Final, id: 5) - 9 questions
        {
            examId: 5,
            questionText: 'What is the chemical symbol for water?',
            questionType: 'multiple_choice',
            optionA: 'H2O',
            optionB: 'CO2',
            optionC: 'O2',
            optionD: 'H2',
            correctAnswer: 'H2O',
            points: 1,
            orderIndex: 0,
        },
        {
            examId: 5,
            questionText: 'The atomic number represents the number of protons',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'True',
            points: 1,
            orderIndex: 1,
        },
        {
            examId: 5,
            questionText: 'What is the pH of a neutral solution?',
            questionType: 'multiple_choice',
            optionA: '7',
            optionB: '0',
            optionC: '14',
            optionD: '10',
            correctAnswer: '7',
            points: 1,
            orderIndex: 2,
        },
        {
            examId: 5,
            questionText: 'What is the most abundant gas in Earth\'s atmosphere?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'Nitrogen',
            points: 2,
            orderIndex: 3,
        },
        {
            examId: 5,
            questionText: 'Which element has the symbol \'Au\'?',
            questionType: 'multiple_choice',
            optionA: 'Gold',
            optionB: 'Silver',
            optionC: 'Copper',
            optionD: 'Iron',
            correctAnswer: 'Gold',
            points: 1,
            orderIndex: 4,
        },
        {
            examId: 5,
            questionText: 'Water boils at 100°C at sea level',
            questionType: 'true_false',
            optionA: 'True',
            optionB: 'False',
            optionC: null,
            optionD: null,
            correctAnswer: 'True',
            points: 1,
            orderIndex: 5,
        },
        {
            examId: 5,
            questionText: 'What type of bond involves sharing electrons?',
            questionType: 'multiple_choice',
            optionA: 'Ionic bond',
            optionB: 'Covalent bond',
            optionC: 'Metallic bond',
            optionD: 'Hydrogen bond',
            correctAnswer: 'Covalent bond',
            points: 2,
            orderIndex: 6,
        },
        {
            examId: 5,
            questionText: 'What is the chemical formula for table salt?',
            questionType: 'short_answer',
            optionA: null,
            optionB: null,
            optionC: null,
            optionD: null,
            correctAnswer: 'NaCl',
            points: 1,
            orderIndex: 7,
        },
        {
            examId: 5,
            questionText: 'What is Avogadro\'s number approximately?',
            questionType: 'multiple_choice',
            optionA: '6.02 × 10^23',
            optionB: '3.14 × 10^8',
            optionC: '9.81 × 10^2',
            optionD: '1.38 × 10^23',
            correctAnswer: '6.02 × 10^23',
            points: 2,
            orderIndex: 8,
        },
    ];

    await db.insert(questions).values(sampleQuestions);
    
    console.log('✅ Questions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});